#include "dm_ddftable.h"
#include "dm_pl_tree.h"
#include "dm_cbfunc.h"

/*
 *  OMA Standard table item
 */
const DMTREE_ITEM g_stInitStdDataTable[] =
        { { 1, ".", ".", "", "node", 0, 0, NULL, DMTREE_OCCUR_One,
                DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET, NULL, NULL,
                NULL, NULL, NULL }, { 1, "DMAcc", "./DMAcc", "", "node", 0, 0,
                NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                DMTREE_ACCESS_ADD | DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL,
                NULL }, { 1, "DevInfo", "./DevInfo", "", "node", 0, 0, NULL,
                DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL, NULL }, { 1, "Ext",
                "./DevInfo/Ext", "", "node", 0, 0, NULL, DMTREE_OCCUR_One,
                DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET, NULL, NULL,
                NULL, NULL, NULL }, { 1, "Bearer", "./DevInfo/Bearer", "",
                "node", 0, 0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT,
                NULL, DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL, NULL }, { 1,
                "DevId", "./DevInfo/DevId", "text/plain", "chr", 0, 0, NULL,
                DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                DMTREE_ACCESS_GET, NULL, NULL, Get_DevInfoDevId_CBFunc, NULL,
                NULL },
                { 1, "Man", "./DevInfo/Man", "text/plain", "chr", 0, 0, NULL,
                        DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL, Get_DevInfoMan_CBFunc,
                        NULL, NULL }, { 1, "Mod", "./DevInfo/Mod", "text/plain",
                        "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET, NULL,
                        NULL, Get_DevInfoMod_CBFunc, NULL, NULL }, { 1, "DmV",
                        "./DevInfo/DmV", "text/plain", "chr", 0, 0, NULL,
                        DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL, Get_DevInfoDmV_CBFunc,
                        NULL, NULL }, { 1, "Lang", "./DevInfo/Lang",
                        "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET, NULL,
                        NULL, Get_DevInfoLang_CBFunc, NULL, NULL }, { 1,
                        "DevDetail", "./DevDetail", "", "node", 0, 0, NULL,
                        DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL, NULL }, { 1,
                        "Ext", "./DevDetail/Ext", "", "node", 0, 0, NULL,
                        DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL, NULL }, { 0,
                        "DMClientTimeOut", "./DevDetail/Ext/DMClientTimeOut",
                        "text/plain", "int", 2, 0, "90", DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL, NULL, NULL,
                        NULL }, { 0, "DataRetryNum",
                        "./DevDetail/Ext/DataRetryNum", "text/plain", "int", 1,
                        0, "3", DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        NULL, NULL, NULL }, { 0, "DataRetryWaitTime",
                        "./DevDetail/Ext/DataRetryWaitTime", "text/plain",
                        "int", 3, 0, "120", DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL, NULL, NULL,
                        NULL },

                { 1, "Bearer", "./DevDetail/Bearer", "", "node", 0, 0, NULL,
                        DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL, NULL }, { 1,
                        "URI", "./DevDetail/URI", "", "node", 0, 0, NULL,
                        DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL, NULL }, { 1,
                        "MaxDepth", "./DevDetail/URI/MaxDepth", "text/plain",
                        "chr", 1, 0, "7", DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET, NULL,
                        NULL, NULL, NULL, NULL }, { 1, "MaxTotLen",
                        "./DevDetail/URI/MaxTotLen", "text/plain", "chr", 3, 0,
                        "127", DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL, NULL }, { 1,
                        "MaxSegLen", "./DevDetail/URI/MaxSegLen", "text/plain",
                        "chr", 2, 0, "63", DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET, NULL,
                        NULL, NULL, NULL, NULL }, { 1, "DevTyp",
                        "./DevDetail/DevTyp", "text/plain", "chr", 0, 0, NULL,
                        DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL,
                        Get_DevDetailDevTyp_CBFunc, NULL, NULL }, { 1, "OEM",
                        "./DevDetail/OEM", "text/plain", "chr", 0, 0, NULL,
                        DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL, Get_DevDetailOEM_CBFunc,
                        NULL, NULL }, { 1, "FwV", "./DevDetail/FwV",
                        "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET, NULL,
                        NULL, Get_DevDetailFwV_CBFunc, NULL, NULL }, { 1, "SwV",
                        "./DevDetail/SwV", "text/plain", "chr", 0, 0, NULL,
                        DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL, Get_DevDetailSwV_CBFunc,
                        NULL, NULL }, { 1, "HwV", "./DevDetail/HwV",
                        "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET, NULL,
                        NULL, Get_DevDetailHwV_CBFunc, NULL, NULL }, { 1,
                        "LrgObj", "./DevDetail/LrgObj", "text/plain", "bool", 0,
                        0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL,
                        Get_DevDetailLrgObj_CBFunc, NULL, NULL },

                { 1, "Settings", "./Settings", "text/plain", "node", 0, 0, NULL,
                        DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL, NULL },

                { 1, "PIM", "./Settings/PIM", "text/plain", "node", 0, 0, NULL,
                        DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL, NULL }, { 0,
                        "Addr", "./Settings/PIM/Addr", "text/plain", "chr", 0,
                        0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        PIMAddrGetFunc, PIMAddrReplaceFunc, NULL }, { 0,
                        "ConnProfile", "./Settings/PIM/ConnProfile",
                        "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        PIMConProGetFunc, PIMConProReplaceFunc, NULL },

                { 0, "AddressBookURI", "./Settings/PIM/AddressBookURI",
                        "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        PIMAddressBookURIGetFunc, PIMAddressBookURIReplaceFunc,
                        NULL },
                { 0, "CalendarURI", "./Settings/PIM/CalendarURI", "text/plain",
                        "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        PIMCalendarURIGetFunc, PIMCalendarURIReplaceFunc, NULL },
                { 0, "PortNbr", "./Settings/PIM/PortNbr", "text/plain", "chr",
                        0, 0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT,
                        NULL, DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL,
                        NULL, PIMPortNbrGetFunc, PIMPortNbrReplaceFunc, NULL },
                { 0, "UserName", "./Settings/PIM/UserName", "text/plain", "chr",
                        0, 0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT,
                        NULL, DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL,
                        NULL, PIMUserNameGetFunc, PIMUserNameReplaceFunc, NULL },
                { 0, "PassWord", "./Settings/PIM/PassWord", "text/plain", "chr",
                        0, 0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT,
                        NULL, DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL,
                        NULL, PIMPassWordGetFunc, PIMPassWordReplaceFunc, NULL },

                { 1, "DM", "./Settings/DM", "text/plain", "node", 0, 0, NULL,
                        DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL, NULL }, { 0,
                        "APN", "./Settings/DM/APN", "text/plain", "chr", 0, 0,
                        NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        DMAPNGetFunc, DMAPNReplaceFunc, NULL },

                { 0, "ConnProfile", "./Settings/DM/ConnProfile", "text/plain",
                        "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        DMConProGetFunc, DMConProReplaceFunc, NULL }, { 0,
                        "UserName", "./Settings/DM/UserName", "text/plain",
                        "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        DMUserNameGetFunc, DMUserNameReplaceFunc, NULL }, { 0,
                        "Password", "./Settings/DM/Password", "text/plain",
                        "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        DMPasswordGetFunc, DMPasswordReplaceFunc, NULL }, { 0,
                        "Proxy", "./Settings/DM/Proxy", "text/plain", "chr", 0,
                        0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        DMProxyGetFunc, DMProxyReplaceFunc, NULL }, { 0, "Port",
                        "./Settings/DM/Port", "text/plain", "chr", 0, 0, NULL,
                        DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        DMPortGetFunc, DMPortReplaceFunc, NULL },

                { 1, "SR", "./Settings/SR", "text/plain", "node", 0, 0, NULL,
                        DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL, NULL }, { 0,
                        "SRNumber", "./Settings/SR/SRNumber", "text/plain",
                        "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        SRSRNumberGetFunc, SRSRNumberReplaceFunc, NULL }, { 0,
                        "SRPort", "./Settings/SR/SRPort", "text/plain", "chr",
                        0, 0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT,
                        NULL, DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL,
                        NULL, SRSRPortGetFunc, SRSRPortReplaceFunc, NULL },

                { 1, "MMS", "./Settings/MMS", "text/plain", "node", 0, 0, NULL,
                        DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL, NULL }, { 0,
                        "MMSC", "./Settings/MMS/MMSC", "text/plain", "chr", 0,
                        0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        MMSMMSCGetFunc, MMSMMSCReplaceFunc, NULL },
                { 0, "ConnProfile", "./Settings/MMS/ConnProfile", "text/plain",
                        "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        MMSConnProfileGetFunc, MMSConnProfileReplaceFunc, NULL },

                { 1, "WAP", "./Settings/WAP", "text/plain", "node", 0, 0, NULL,
                        DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL, NULL },
                { 0, "ConnProfile", "./Settings/WAP/ConnProfile", "text/plain",
                        "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        WAPConnProfileGetFunc, WAPConnProfileReplaceFunc, NULL },
                { 0, "ProxyAddr", "./Settings/WAP/ProxyAddr", "text/plain",
                        "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        WAPProxyAddrGetFunc, WAPProxyAddrReplaceFunc, NULL },
                { 0, "ProxyPortNbr", "./Settings/WAP/ProxyPortNbr",
                        "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        WAPProxyPortNbrGetFunc, WAPProxyPortNbrReplaceFunc, NULL },
                { 0, "StartPage", "./Settings/WAP/StartPage", "text/plain",
                        "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        WAPStartPageGetFunc, WAPStartPageReplaceFunc, NULL }, {
                        0, "UserName", "./Settings/WAP/UserName", "text/plain",
                        "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        WAPUserNameGetFunc, WAPUserNameReplaceFunc, NULL }, { 0,
                        "PassWord", "./Settings/WAP/PassWord", "text/plain",
                        "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        WAPPassWordGetFunc, WAPPassWordReplaceFunc, NULL }, { 0,
                        "APN", "./Settings/WAP/APN", "text/plain", "chr", 0, 0,
                        NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        WAPAPNGetFunc, WAPAPNReplaceFunc, NULL },

                { 1, "GPRS", "./Settings/GPRS", "text/plain", "node", 0, 0,
                        NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL, NULL },

                { 1, "CMNet", "./Settings/GPRS/CMNet", "text/plain", "node", 0,
                        0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL, NULL },
                { 0, "APN", "./Settings/GPRS/CMNet/APN", "text/plain", "chr", 0,
                        0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        GPRSCmnetAPNGetFunc, GPRSCmnetAPNReplaceFunc, NULL }, {
                        0, "UserName", "./Settings/GPRS/CMNet/UserName",
                        "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        GPRSCmnetUserNameGetFunc, GPRSCmnetUserNameReplaceFunc,
                        NULL }, { 0, "PassWord",
                        "./Settings/GPRS/CMNet/PassWord", "text/plain", "chr",
                        0, 0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT,
                        NULL, DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL,
                        NULL, GPRSCmnetPassWordGetFunc,
                        GPRSCmnetPassWordReplaceFunc, NULL }, { 0, "ProxyAddr",
                        "./Settings/GPRS/CMNet/ProxyAddr", "text/plain", "chr",
                        0, 0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT,
                        NULL, DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL,
                        NULL, GPRSCmnetProxyAddrGetFunc,
                        GPRSCmnetProxyAddrReplaceFunc, NULL }, { 0,
                        "ProxyPortNbr", "./Settings/GPRS/CMNet/ProxyPortNbr",
                        "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        GPRSCmnetProxyPortNbrGetFunc,
                        GPRSCmnetProxyPortNbrReplaceFunc, NULL },

                { 1, "CMWap", "./Settings/GPRS/CMWap", "text/plain", "node", 0,
                        0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL, NULL },
                { 0, "APN", "./Settings/GPRS/CMWap/APN", "text/plain", "chr", 0,
                        0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        GPRSCmwapAPNGetFunc, GPRSCmwapAPNReplaceFunc, NULL }, {
                        0, "UserName", "./Settings/GPRS/CMWap/UserName",
                        "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        GPRSCmwapUserNameGetFunc, GPRSCmwapUserNameReplaceFunc,
                        NULL }, { 0, "PassWord",
                        "./Settings/GPRS/CMWap/PassWord", "text/plain", "chr",
                        0, 0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT,
                        NULL, DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL,
                        NULL, GPRSCmwapPassWordGetFunc,
                        GPRSCmwapPassWordReplaceFunc, NULL }, { 0, "ProxyAddr",
                        "./Settings/GPRS/CMWap/ProxyAddr", "text/plain", "chr",
                        0, 0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT,
                        NULL, DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL,
                        NULL, GPRSCmwapProxyAddrGetFunc,
                        GPRSCmwapProxyAddrReplaceFunc, NULL }, { 0,
                        "ProxyPortNbr", "./Settings/GPRS/CMWap/ProxyPortNbr",
                        "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        GPRSCmwapProxyPortNbrGetFunc,
                        GPRSCmwapProxyPortNbrReplaceFunc, NULL },

                { 1, "Streaming", "./Settings/Streaming", "text/plain", "node",
                        0, 0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT,
                        NULL, DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL, NULL },
                { 0, "Name", "./Settings/Streaming/Name", "text/plain", "chr",
                        0, 0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT,
                        NULL, DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL,
                        NULL, StreamingNameGetFunc, StreamingNameReplaceFunc,
                        NULL },
                { 0, "Proxy", "./Settings/Streaming/Proxy", "text/plain", "chr",
                        0, 0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT,
                        NULL, DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL,
                        NULL, StreamingProxyGetFunc, StreamingProxyReplaceFunc,
                        NULL }, { 0, "ProxyPort",
                        "./Settings/Streaming/ProxyPort", "text/plain", "chr",
                        0, 0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT,
                        NULL, DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL,
                        NULL, StreamingProxyPortGetFunc,
                        StreamingProxyPortReplaceFunc, NULL }, { 0,
                        "ConnProfile", "./Settings/Streaming/ConnProfile",
                        "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        StreamingConnProfileGetFunc,
                        StreamingConnProfileReplaceFunc, NULL }, { 0, "NetInfo",
                        "./Settings/Streaming/NetInfo", "text/plain", "chr", 0,
                        0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        StreamingNetInfoGetFunc, StreamingNetInfoReplaceFunc,
                        NULL }, { 0, "MinUdpPort",
                        "./Settings/Streaming/MinUdpPort", "text/plain", "chr",
                        0, 0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT,
                        NULL, DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL,
                        NULL, StreamingMinUdpPortGetFunc,
                        StreamingMinUdpPortReplaceFunc, NULL }, { 0,
                        "MaxUdpPort", "./Settings/Streaming/MaxUdpPort",
                        "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        StreamingMaxUdpPortGetFunc,
                        StreamingMaxUdpPortReplaceFunc, NULL },
                //wap push mail add
                { 1, "PushMail", "./Settings/PushMail", "text/plain", "node", 0,
                        0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL, NULL }, { 0,
                        "SendUseSecCon", "./Settings/PushMail/SendUseSecCon",
                        "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        PushMailSendUseSecConGetFunc,
                        PushMailSendUseSecConReplaceFunc, NULL }, { 0,
                        "SendServer", "./Settings/PushMail/SendServer",
                        "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        PushMailSendServerGetFunc,
                        PushMailSendServerReplaceFunc, NULL }, { 0, "SendPort",
                        "./Settings/PushMail/SendPort", "text/plain", "chr", 0,
                        0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        PushMailSendPortGetFunc, PushMailSendPortReplaceFunc,
                        NULL },
                { 0, "RecvPro", "./Settings/PushMail/RecvPro", "text/plain",
                        "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        PushMailRecvProGetFunc, PushMailRecvProReplaceFunc, NULL },
                { 0, "RecvUseSecCon", "./Settings/PushMail/RecvUseSecCon",
                        "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        PushMailRecvUseSecConGetFunc,
                        PushMailRecvUseSecConReplaceFunc, NULL }, { 0,
                        "RecvServer", "./Settings/PushMail/RecvServer",
                        "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        PushMailRecvServerGetFunc,
                        PushMailRecvServerReplaceFunc, NULL }, { 0, "RecvPort",
                        "./Settings/PushMail/RecvPort", "text/plain", "chr", 0,
                        0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        PushMailRecvPortGetFunc, PushMailRecvPortReplaceFunc,
                        NULL }, { 0, "ConnProfile",
                        "./Settings/PushMail/ConnProfile", "text/plain", "chr",
                        0, 0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT,
                        NULL, DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL,
                        NULL, PushMailConnProfileGetFunc,
                        PushMailConnProfileReplaceFunc, NULL },
                // Add  AGPS
                { 1, "AGPS", "./Settings/AGPS", "text/plain", "node", 0, 0,
                        NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_PERMANENT, NULL,
                        DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL, NULL },
                { 0, "AGPSServer", "./Settings/AGPS/AGPSServer", "text/plain",
                        "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        AgpsServerPortGetFunc, AgpsServerPortReplaceFunc, NULL },
                { 0, "ConnProfile", "./Settings/AGPS/ConnProfile", "text/plain",
                        "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                        DMTREE_SCOPE_PERMANENT, NULL, DMTREE_ACCESS_GET
                                | DMTREE_ACCESS_REPLACE, NULL, NULL,
                        AgpsConnProfileGetFunc, AgpsConnProfileReplaceFunc, NULL },
                // End Table
                { 0, "", "", "", "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } };

/*
 *  OMA Account standard table item
 */
const DMTREE_ITEM g_stAccStdDataTable[] = { { 0, "*", "*", "", "node", 0, 0,
        NULL, DMTREE_OCCUR_ZeroOrMore, DMTREE_SCOPE_DYNAMIC, NULL,
        DMTREE_ACCESS_DELETE | DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL,
        NULL, NULL, NULL, NULL }, { 0, "AppID", "AppID", "text/plain", "chr", 0,
        0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_DYNAMIC, NULL,
        DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL, NULL }, { 0, "ServerID",
        "ServerID", "text/plain", "chr", 1, 0, "1", DMTREE_OCCUR_One,
        DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL,
        NULL }, { 0, "Name", "Name", "text/plain", "chr", 0, 0, NULL,
        DMTREE_OCCUR_ZeroOrOne, DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET,
        NULL, NULL, NULL, NULL, NULL }, { 0, "PrefConRef", "PrefConRef",
        "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_ZeroOrOne,
        DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL,
        NULL }, { 0, "ToConRef", "ToConRef", "text/plain", "node", 0, 0, NULL,
        DMTREE_OCCUR_ZeroOrOne, DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET,
        NULL, NULL, NULL, NULL, NULL }, { 0, "ToConRef/ConRef",
        "ToConRef/ConRef", "text/plain", "chr", 0, 0, NULL,
        DMTREE_OCCUR_ZeroOrOne, DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET,
        NULL, NULL, NULL, NULL, NULL },

{ 0, "AppAddr", "AppAddr", "text/plain", "node", 0, 0, NULL, DMTREE_OCCUR_One,
        DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL,
        NULL }, { 0, "AppAddr/Addr", "AppAddr/Addr", "text/plain", "chr", 0, 0,
        NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET,
        NULL, NULL, Get_ServerAddr_CBFunc, NULL, NULL }, { 0,
        "AppAddr/AddrType", "AppAddr/AddrType", "text/plain", "chr", 0, 0, NULL,
        DMTREE_OCCUR_One, DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET, NULL,
        NULL, NULL, NULL, NULL }, { 0, "AppAddr/Port", "AppAddr/Port",
        "text/plain", "node", 0, 0, NULL, DMTREE_OCCUR_ZeroOrOne,
        DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL,
        NULL }, { 0, "AppAddr/Port/PortNbr", "AppAddr/Port/PortNbr",
        "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_ZeroOrOne,
        DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL,
        NULL },

{ 0, "AAuthPref", "AAuthPref", "text/plain", "chr", 0, 0, NULL,
        DMTREE_OCCUR_ZeroOrOne, DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET,
        NULL, NULL, NULL, NULL, NULL },

{ 0, "AppAuth", "AppAuth", "text/plain", "node", 0, 0, NULL, DMTREE_OCCUR_One,
        DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET, NULL, NULL, NULL, NULL,
        NULL },

{ 0, "AppAuth/Server", "AppAuth/Server", "text/plain", "node", 0, 0, NULL,
        DMTREE_OCCUR_One, DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET, NULL,
        NULL, NULL, NULL, NULL }, { 0, "AppAuth/Server/AAuthLevel",
        "AppAuth/Server/AAuthLevel", "text/plain", "chr", 0, 0, NULL,
        DMTREE_OCCUR_One, DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET, NULL,
        NULL, NULL, NULL, NULL }, { 0, "AppAuth/Server/AAuthType",
        "AppAuth/Server/AAuthType", "text/plain", "chr", 0, 0, NULL,
        DMTREE_OCCUR_One, DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET, NULL,
        NULL, NULL, NULL, NULL }, { 0, "AppAuth/Server/AAuthName",
        "AppAuth/Server/AAuthName", "text/plain", "chr", 0, 0, NULL,
        DMTREE_OCCUR_ZeroOrOne, DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET,
        NULL, NULL, NULL, NULL, NULL }, { 0, "AppAuth/Server/AAuthSecret",
        "AppAuth/Server/AAuthSecret", "text/plain", "chr", 0, 0, NULL,
        DMTREE_OCCUR_ZeroOrOne, DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET
                | DMTREE_ACCESS_REPLACE, NULL, NULL, NULL, NULL, NULL }, { 0,
        "AppAuth/Server/AAuthData", "AppAuth/Server/AAuthData", "text/plain",
        "chr", 0, 0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_DYNAMIC, NULL,
        DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL, NULL,
        ServerNonceGetFunc, ServerNonceReplaceFunc, NULL }, { 0,
        "AppAuth/Server/PrevAAuthData", "AppAuth/Server/PrevAAuthData",
        "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_One, DMTREE_SCOPE_DYNAMIC,
        NULL, DMTREE_ACCESS_GET | DMTREE_ACCESS_REPLACE, NULL, NULL, NULL, NULL,
        NULL },

{ 0, "AppAuth/Client", "AppAuth/Client", "text/plain", "node", 0, 0, NULL,
        DMTREE_OCCUR_One, DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET
                | DMTREE_ACCESS_REPLACE, NULL, NULL, NULL, NULL, NULL },
        { 0, "AppAuth/Client/AAuthLevel", "AppAuth/Client/AAuthLevel",
                "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET
                        | DMTREE_ACCESS_REPLACE, NULL, NULL, NULL, NULL, NULL },
        { 0, "AppAuth/Client/AAuthType", "AppAuth/Client/AAuthType",
                "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET
                        | DMTREE_ACCESS_REPLACE, NULL, NULL, NULL, NULL, NULL },
        { 0, "AppAuth/Client/AAuthName", "AppAuth/Client/AAuthName",
                "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_ZeroOrOne,
                DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET
                        | DMTREE_ACCESS_REPLACE, NULL, NULL, NULL, NULL, NULL },
        { 0, "AppAuth/Client/AAuthSecret", "AppAuth/Client/AAuthSecret",
                "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_ZeroOrOne,
                DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET
                        | DMTREE_ACCESS_REPLACE, NULL, NULL, NULL, NULL, NULL },
        { 0, "AppAuth/Client/AAuthData", "AppAuth/Client/AAuthData",
                "text/plain", "chr", 0, 0, NULL, DMTREE_OCCUR_One,
                DMTREE_SCOPE_DYNAMIC, NULL, DMTREE_ACCESS_GET
                        | DMTREE_ACCESS_REPLACE, NULL, NULL, ClientNonceGetFunc,
                ClientNonceReplaceFunc, NULL },

        // End Table
        { 0, "", "", "", "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } };

