/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qualcomm_sensors_sensortest_SensorTest */

#ifndef _Included_com_qualcomm_sensors_sensortest_SensorTest
#define _Included_com_qualcomm_sensors_sensortest_SensorTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qualcomm_sensors_sensortest_SensorTest
 * Method:    runNativeSensorTest
 * Signature: (IIIZZ)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_sensors_sensortest_SensorTest_runNativeSensorTest__IIIZZ
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     com_qualcomm_sensors_sensortest_SensorTest
 * Method:    runNativeSensorTest
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_sensors_sensortest_SensorTest_runNativeSensorTest__III
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_qualcomm_sensors_sensortest_SensorTest
 * Method:    setNativeRawDataMode
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_sensors_sensortest_SensorTest_setNativeRawDataMode
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_qualcomm_sensors_sensortest_SensorTest
 * Method:    getNativeRawDataMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_sensors_sensortest_SensorTest_getNativeRawDataMode
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif

