#! /bin/sh

set -e

case "$1" in
start)
    echo -n "Starting irsc_util: "
    /usr/bin/irsc_util /etc/sec_config
    echo "done"
    ;;
  stop)
    echo "done"
    ;;
  restart)
    echo "done"
    ;;
  *)
    echo "Usage irsc_util{ start | stop | restart }" >&2
    exit 1
    ;;
esac

exit 0
