#! /bin/sh
#
#Copyright (c) 2011 Qualcomm Technologies, Inc.  All Rights Reserved.
#Qualcomm Technologies Proprietary and Confidential.

# qmuxd        init.d script to start QMI's qmuxd daemon

set -e

case "$1" in
  start)
        echo -n "Starting qmuxd: "
        start-stop-daemon -S -b -a /usr/bin/qmuxd
        echo "done"
        ;;
  stop)
        echo -n "Stopping qmuxd: "
        start-stop-daemon -K -n qmuxd
        echo "done"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage qmuxd { start | stop | restart}" >&2
        exit 1
        ;;
esac


exit 0
