
MODULE_NAME        := QMICL_HELPER
MODULE_ROOT        := ../../data-noship
MODULE_CFLAGS      :=
MODULE_C_SOURCES   := $(wildcard *.c)
MODULE_CPP_SOURCES :=
MODULE_HEADERS     := $(wildcard *.h)
MODULE_LIB_LOC     := ../lib
MODULE_LIB_TARGET  := libqmi_client_helper.so
MODULE_BIN_LOC     :=
MODULE_BIN_TARGET  :=

include $(MODULE_ROOT)/test.mk

