/*****************************************************************************
  @FILE     sns_sam_basic_gestures.idl

  @BRIEF    Message definition for Basic Gestures.

  @DESCRIPTION
  This file defines Basic Gestures messages used by Basic Gestures algo services,

  As prerequisite, the sensor algorithm must use the common Interface
  defined in the Sensor Algorithms framework.

  The messages defined herein will be passed to the Sensor framework using
  the sensor1_write() API.

  @COPYRIGHT
  Copyright (c) 2011-2014 Qualcomm Technologies, Inc.  All Rights Reserved
  Qualcomm Technologies Proprietary and Confidential.

*****************************************************************************/
include "sns_sam_common_v01.idl";

revision 4;

const SNS_SAM_BASIC_GESTURES_SUID = 0xc8c699d420dc5acc;

/** ENUMs are for reference only, uint8 is used instead */

//! @ENUM   SNS_SAM_BASIC_GESTURES_EVENT_ENUM
enum {
  BASIC_GESTURE_PUSH              = 1,
  /**< Phone is pulled away from the user in a direction perpendicular to the screen. */
  BASIC_GESTURE_PULL              = 2,
  /**< Phone is pulled toward the user in a direction perpendicular to the screen. */
  BASIC_GESTURE_SHAKE_AXIS_LEFT   = 3,
  /**< Phone is shaken toward the left. */
  BASIC_GESTURE_SHAKE_AXIS_RIGHT  = 4,
  /**< Phone is shaken toward the right. */
  BASIC_GESTURE_SHAKE_AXIS_TOP    = 5,
  /**< Phone is shaken toward the top. */
  BASIC_GESTURE_SHAKE_AXIS_BOTTOM = 6,
  /**< Phone is shaken toward the bottom. */
  BASIC_GESTURE_SHAKE_AXIS_UNKNOWN = 7
  /**< Phone is shaken, but phone shake direction cannot be clearly determined. */
} sns_sam_basic_gestures_event_e;

/* Following are message definitions shared by all Basic Gestures-related services */

//============================================================================
/** @COMMAND SNS_SAM_BASIC_GESTURES_ENABLE
    @BRIEF Enables a sensor algorithm.
*/
//============================================================================

//! @MSG     SNS_SAM_BASIC_GESTURES_ENABLE_REQ
//! @TYPE    Request
//! @SENDER  Client
//----------------------------------------------------------------------------

message {
  optional uint32 sample_rate;
  /**< Sample rate in Hz; Q16 format. */
  optional int32 sleep;
  /**< Sleep time in seconds after a gesture is generated; Q16 format. */
  optional int32 push_threshold;
  /**< Push threshold m/s/s; Q16 format. Range: 1G to 5G */
  optional int32 pull_threshold;
  /**< Pull threshold m/s/s; Q16 format. Range: 1G to 5G */
  optional int32 shake_threshold;
  /**< Shake threshold m/s/s; Q16 format. Range: 1G to 5G */
  //! @VERSION 1.2
  optional sns_suspend_notification_s notify_suspend;
  /**< Identifies whether indications for this request are to be sent
       when the processor is in the Suspend state.

       If this field is not specified, the default value is set to:
       notify_suspend->proc_type                  = SNS_PROC_APPS
       notify_suspend->send_indications_during_suspend  = FALSE

       This field does not have any bearing on error indication
       messages, which are sent even during Suspend.
    */
} sns_sam_basic_gestures_enable_req_msg;

//! @MSG     SNS_SAM_BASIC_GESTURES_ENABLE_RESP
//! @TYPE    Response
//! @SENDER  Service
//----------------------------------------------------------------------------

message {
  mandatory sns_common_resp_s                resp = 2;
  /**< Common response message. */
  optional uint8                             instance_id;
  /**< Instance ID, which is maintained/assigned by the SAM.
       The client must use this instance ID for future messages associated with
       the current algorithm instance.
  */
} sns_sam_basic_gestures_enable_resp_msg;


//============================================================================
/** @COMMAND SNS_SAM_BASIC_GESTURES_DISABLE
    @BRIEF Disables a sensor algorithm.
*/
//============================================================================

//! @MSG     SNS_SAM_BASIC_GESTURES_DISABLE_REQ
//! @TYPE    Request
//! @SENDER  Client
//----------------------------------------------------------------------------

message {
  mandatory uint8                             instance_id;
  /**< Identifies the algorithm instance.  */
} sns_sam_basic_gestures_disable_req_msg;

//! @MSG     SNS_SAM_BASIC_GESTURES_DISABLE_RESP
//! @TYPE    Response
//! @SENDER  Service
//----------------------------------------------------------------------------

message {
  mandatory sns_common_resp_s                resp = 2;
  /**< Common response message. */
  optional uint8                             instance_id;
  /**< Identifies the algorithm instance.  */
} sns_sam_basic_gestures_disable_resp_msg;


//============================================================================
/** @COMMAND SNS_SAM_BASIC_GESTURES_REPORT
    @BRIEF Output report from a sensor algorithm.
*/
//============================================================================

//! @MSG     SNS_SAM_BASIC_GESTURES_REPORT_IND
//! @TYPE    Indication
//! @SENDER  Service
//----------------------------------------------------------------------------

message {
  mandatory uint8                             instance_id;
  /**< Identifies the algorithm instance.  */
  mandatory uint32                            timestamp;
  /**< Timestamp of the input that caused this indication; in SSC ticks */
  mandatory sns_sam_basic_gestures_event_e    state;
  /**< State. */
} sns_sam_basic_gestures_report_ind_msg;


//============================================================================
/** @COMMAND SNS_SAM_BASIC_GESTURES_GET_REPORT
    @BRIEF Gets the report output from a sensor algorithm.
*/
//============================================================================

//! @MSG     SNS_SAM_BASIC_GESTURES_GET_REPORT_REQ
//! @TYPE    Request
//! @SENDER  Client
//----------------------------------------------------------------------------

message {
  mandatory uint8                             instance_id;
  /**< Identifies the algorithm instance.  */
} sns_sam_basic_gestures_get_report_req_msg;

//! @MSG     SNS_SAM_BASIC_GESTURES_GET_REPORT_RESP
//! @TYPE    Response
//! @SENDER  Service
//----------------------------------------------------------------------------

message {
  mandatory sns_common_resp_s                resp = 2;
  /**< Common response message. */
  optional uint8                             instance_id;
  /**< Identifies the algorithm instance.  */
  optional uint32                            timestamp;
  /**< Timestamp at which this report is fetched; in SSC ticks. */
  optional sns_sam_basic_gestures_event_e    state;
  /**< State. */
} sns_sam_basic_gestures_get_report_resp_msg;


//============================================================================
/** @COMMAND SNS_SAM_BASIC_GESTURES_ERROR
    @BRIEF Asynchronous error report from a sensor algorithm.
*/
//============================================================================

//! @MSG     SNS_SAM_BASIC_GESTURES_ERROR_IND
//! @TYPE    Indication
//! @SENDER  Service
//============================================================================

message {
  mandatory uint8                            error;
  /**< Sensors error code. */
  mandatory uint8                            instance_id;
  /**< Identifies the algorithm instance.  */
} sns_sam_basic_gestures_error_ind_msg;

//============================================================================
/** @COMMAND SNS_SAM_BASIC_GESTURES_CANCEL
    @BRIEF Cancels all requests to the algorithm service.
*/
//============================================================================

//============================================================================
/** @COMMAND SNS_SAM_BASIC_GESTURES_VERSION
    @BRIEF Requests the algorithm service version.
*/
//============================================================================

//============================================================================
// Service definition
//============================================================================
service SNS_SAM_BASIC_GESTURES_SVC {
  //! @ID SNS_SAM_BASIC_GESTURES_CANCEL
  sns_common_cancel_req_msg        SNS_SAM_BASIC_GESTURES_CANCEL_REQ,
  sns_common_cancel_resp_msg       SNS_SAM_BASIC_GESTURES_CANCEL_RESP
    = 0x00;

  //! @ID SNS_SAM_BASIC_GESTURES_VERSION
  sns_common_version_req_msg       SNS_SAM_BASIC_GESTURES_VERSION_REQ,
  sns_common_version_resp_msg      SNS_SAM_BASIC_GESTURES_VERSION_RESP
    = 0x01;

  //! @ID SNS_SAM_BASIC_GESTURES_ENABLE
  sns_sam_basic_gestures_enable_req_msg       SNS_SAM_BASIC_GESTURES_ENABLE_REQ,
  sns_sam_basic_gestures_enable_resp_msg      SNS_SAM_BASIC_GESTURES_ENABLE_RESP
    = 0x02;

  //! @ID SNS_SAM_BASIC_GESTURES_DISABLE
  sns_sam_basic_gestures_disable_req_msg      SNS_SAM_BASIC_GESTURES_DISABLE_REQ,
  sns_sam_basic_gestures_disable_resp_msg     SNS_SAM_BASIC_GESTURES_DISABLE_RESP
    = 0x03;

  //! @ID SNS_SAM_BASIC_GESTURES_GET_REPORT
  sns_sam_basic_gestures_get_report_req_msg   SNS_SAM_BASIC_GESTURES_GET_REPORT_REQ,
  sns_sam_basic_gestures_get_report_resp_msg  SNS_SAM_BASIC_GESTURES_GET_REPORT_RESP
    = 0x04;

  //! @ID SNS_SAM_BASIC_GESTURES_REPORT
  sns_sam_basic_gestures_report_ind_msg       SNS_SAM_BASIC_GESTURES_REPORT_IND
    = 0x05;

  //! @ID SNS_SAM_BASIC_GESTURES_ERROR
  sns_sam_basic_gestures_error_ind_msg        SNS_SAM_BASIC_GESTURES_ERROR_IND
    = 0x06;

  //! @ID SNS_SAM_GET_ALGO_ATTRIBUTES
  sns_sam_get_algo_attrib_req_msg  SNS_SAM_BASIC_GESTURES_GET_ATTRIBUTES_REQ,
  sns_sam_get_algo_attrib_resp_msg SNS_SAM_BASIC_GESTURES_GET_ATTRIBUTES_RESP
    = 0x24;

} = SNS_QMI_SVC_ID_25;

//============================================================================
// File footer
//============================================================================
/**
@FOOTER
*/

//============================================================================
// End of Module
//============================================================================

