/* Copyright (c) 2011-2012 Qualcomm Technologies, Inc.  All Rights Reserved.
 * Qualcomm Technologies Proprietary and Confidential.
 */

#ifndef ACDB_LOADER_DEF_H

#define USE_8660_LEGACY_ACDB_INTF

#define ACDB_BLOCK_SIZE		4096
#define MAX_BLOCK_SIZE		ACDB_BLOCK_SIZE
#define NUM_NETWORKS		12
#define NUM_AUDPROC_BLOCKS	6
#define NUM_VOCPROC_BLOCKS	3 * NUM_NETWORKS
#define NUM_CVP_BLOCKS		2 * NUM_NETWORKS
#define NUM_AFE_BLOCKS		0
#define NUM_ANC_BLOCKS	 	1
#define NUM_CAL_BLOCKS		(NUM_AUDPROC_BLOCKS + NUM_VOCPROC_BLOCKS + \
				NUM_ANC_BLOCKS)
#define NUM_AUDPROC_PATHS	2
#define NUM_AUDVOL_PATHS	2
#define ACDB_VOCSTRM_OFFSET	NUM_NETWORKS
#define ACDB_VOCVOL_OFFSET	NUM_NETWORKS + ACDB_VOCSTRM_OFFSET
#define ACDB_AUDSTRM_OFFSET	NUM_VOCPROC_BLOCKS + NUM_AUDPROC_PATHS
#define ACDB_AUDVOL_OFFSET	ACDB_AUDSTRM_OFFSET + NUM_AUDPROC_PATHS
#define ACDB_ANC_OFFSET		(ACDB_AUDVOL_OFFSET + NUM_AUDVOL_PATHS)
#define ACDB_AFE_OFFSET		0
#define AUDPROC_BUFFER_SIZE	ACDB_BLOCK_SIZE * NUM_AUDPROC_BLOCKS
#define VOCPROC_BUFFER_SIZE	ACDB_BLOCK_SIZE * NUM_VOCPROC_BLOCKS
#define CVP_BUFFER_SIZE		ACDB_BLOCK_SIZE * NUM_CVP_BLOCKS
#define ACDB_BUFFER_SIZE	ACDB_BLOCK_SIZE * NUM_CAL_BLOCKS

#define VOICE_CAL_IN_BAND	1
#define SUPPORT_VOLTE_CAL	0
#define ACDB_NETWORK_ID_VOLTE	0

	/* Partition the PMEM into the following region for voice/audio cal
	 * voice blocks 0-23 & 24-35 are now place squentially in two big blocks
	 * one 24 x 4096 and the other 12 x 4096
	 * [0 * 4096] =  VOICE_VOCPROC_VOIP_NB
	 * [1 * 4096] =  VOICE_VOCPROC_VOIP_WB
	 * [2 * 4096] =  VOICE_VOCPROC_VOIP_WV
	 * [3 * 4096] =  VOICE_VOCPROC_CDMA_NB
	 * [4 * 4096] =  VOICE_VOCPROC_CDMA_WB
	 * [5 * 4096] =  VOICE_VOCPROC_CDMA_WV
	 * [6 * 4096] =  VOICE_VOCPROC_GSM_NB
	 * [7 * 4096] =  VOICE_VOCPROC_GSM_WB
	 * [8 * 4096] =  VOICE_VOCPROC_GSM_WV
	 * [9 * 4096] =  VOICE_VOCPROC_WCDMA_NB
	 * [10 * 4096] = VOICE_VOCPROC_WCDMA_WB
	 * [11 * 4096] = VOICE_VOCPROC_WCDMA_WV
	 * [12 * 4096] = VOICE_VOCVOL_VOIP_NB
	 * [13 * 4096] = VOICE_VOCVOL_VOIP_WB
	 * [14 * 4096] = VOICE_VOCVOL_VOIP_WV
	 * [15 * 4096] = VOICE_VOCVOL_CDMA_NB
	 * [16 * 4096] = VOICE_VOCVOL_CDMA_WB
	 * [17 * 4096] = VOICE_VOCVOL_CDMA_WV
	 * [18 * 4096] = VOICE_VOCVOL_GSM_NB
	 * [19 * 4096] = VOICE_VOCVOL_GSM_WB
	 * [20 * 4096] = VOICE_VOCVOL_GSM_WV
	 * [21 * 4096] = VOICE_VOCVOL_WCDMA_NB
	 * [22 * 4096] = VOICE_VOCVOL_WCDMA_WB
	 * [23 * 4096] = VOICE_VOCVOL_WCDMA_WV
	 * <End of first voice cal block>
	 * [24 * 4096] = VOICE_VOCSTRM_VOIP_NB
	 * [25 * 4096] = VOICE_VOCSTRM_VOIP_WB
	 * [26 * 4096] = VOICE_VOCSTRM_VOIP_WV
	 * [27 * 4096] = VOICE_VOCSTRM_CDMA_NB
	 * [28 * 4096] = VOICE_VOCSTRM_CDMA_WB
	 * [29 * 4096] = VOICE_VOCSTRM_CDMA_WV
	 * [30 * 4096] = VOICE_VOCSTRM_GSM_NB
	 * [31 * 4096] = VOICE_VOCSTRM_GSM_WB
	 * [32 * 4096] = VOICE_VOCSTRM_GSM_WV
	 * [33 * 4096] = VOICE_VOCSTRM_WCDMA_NB
	 * [34 * 4096] = VOICE_VOCSTRM_WCDMA_WB
	 * [35 * 4096] = VOICE_VOCSTRM_WCDMA_WV
	 * <End of second voice cal block>
	 * [36 * 4096] = AUDPROC_RX_CAL
	 * [37 * 4096] = AUDPROC_TX_CAL
	 * [38 * 4096] = AUDPROC_RX_STREAM_CAL
	 * [39 * 4096] = AUDPROC_TX_STREAM_CAL
	 * [40 * 4096] = AUDPROC_RX_VOL_CAL
	 * [41 * 4096] = AUDPROC_TX_VOL_CAL
	 * [42 * 4096] = ANC_CAL
	 */

#endif /* ACDB_LOADER_DEF_H */
