/*
 *    Copyright (c) 2012-2013 Qualcomm Technologies, Inc. All Rights Reserved.
 *    Qualcomm Technologies Proprietary and Confidential.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qualcomm_listen_ListenMasterControl */

#ifndef _Included_com_qualcomm_listen_ListenMasterControl
#define _Included_com_qualcomm_listen_ListenMasterControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qualcomm_listen_ListenMasterControl
 * Method:    setParam
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenMasterControl_setParam
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_qualcomm_listen_ListenMasterControl
 * Method:    getParam
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qualcomm_listen_ListenMasterControl_getParam
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
