/*
 *    Copyright (c) 2012-2014 Qualcomm Technologies, Inc. All Rights Reserved.
 *    Qualcomm Technologies Proprietary and Confidential.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qualcomm_listen_ListenReceiver */

#ifndef _Included_com_qualcomm_listen_ListenReceiver
#define _Included_com_qualcomm_listen_ListenReceiver
#ifdef __cplusplus
extern "C" {
#endif

#undef com_qualcomm_listen_ListenReceiver_UNDEFINED_RECEIVER_TYPE
#define com_qualcomm_listen_ListenReceiver_UNDEFINED_RECEIVER_TYPE 0L
#undef com_qualcomm_listen_ListenReceiver_MASTERCONTROL_RECEIVER_TYPE
#define com_qualcomm_listen_ListenReceiver_MASTERCONTROL_RECEIVER_TYPE 1L
#undef com_qualcomm_listen_ListenReceiver_VWUSESSION_RECEIVER_TYPE
#define com_qualcomm_listen_ListenReceiver_VWUSESSION_RECEIVER_TYPE 2L

/*
 * Class:     com_qualcomm_listen_ListenReceiver
 * Method:    init
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenReceiver_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_qualcomm_listen_ListenReceiver
 * Method:    release
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenReceiver_release
  (JNIEnv *, jobject);

/*
 * Class:     com_qualcomm_listen_ListenReceiver
 * Method:    getDetectionStrings
 * Signature: (ILcom/qualcomm/listen/ListenTypes/EventData;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenReceiver_getDetectionStrings
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
