/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qualcomm_timeservice_TimeServiceBroadcastReceiver */

#ifndef _Included_com_qualcomm_timeservice_TimeServiceBroadcastReceiver
#define _Included_com_qualcomm_timeservice_TimeServiceBroadcastReceiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qualcomm_timeservice_TimeServiceBroadcastReceiver
 * Method:    setTimeServicesUserTime
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qualcomm_timeservice_TimeServiceBroadcastReceiver_setTimeServicesUserTime
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
