set echo off;
-- Copyright (C) 2013 Mimer Information Technology AB, info@mimer.com
set message off;
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 200 from files);
delete from files where "_id" > (select max("_id") - 200 from files);
delete from files where "_id" > (select max("_id") - 200 from files);
delete from files where "_id" > (select max("_id") - 200 from files);
delete from files where "_id" > (select max("_id") - 200 from files);
delete from files;
delete from thumbnails;
delete from artists;
delete from albums;
delete from album_art;
delete from video;
delete from videothumbnails;

alter sequence files_id_seq restart with 1;
alter sequence artist_id_seq restart with 1;
alter sequence albums_id_seq restart with 1;

enter 'media_external' using 'nopass';
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 200 from files);
delete from files where "_id" > (select max("_id") - 200 from files);
delete from files where "_id" > (select max("_id") - 200 from files);
delete from files where "_id" > (select max("_id") - 200 from files);
delete from files where "_id" > (select max("_id") - 200 from files);
delete from files;
delete from thumbnails;
delete from artists;
delete from albums;
delete from audio_genres;
delete from album_art;
delete from video;
delete from videothumbnails;
delete from audio_genres_map;
delete from audio_playlists_map;
alter sequence files_id_seq restart with 1;
alter sequence artist_id_seq restart with 1;
alter sequence albums_id_seq restart with 1;
alter sequence audio_genres_id_seq restart with 1;
alter sequence audio_genres_map_id_seq restart with 1;
alter sequence audio_playlists_map_id_seq restart with 1;

leave;

enter 'media_external_1' using 'nopass';
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 200 from files);
delete from files where "_id" > (select max("_id") - 200 from files);
delete from files where "_id" > (select max("_id") - 200 from files);
delete from files where "_id" > (select max("_id") - 200 from files);
delete from files where "_id" > (select max("_id") - 200 from files);
delete from files;
delete from thumbnails;
delete from artists;
delete from albums;
delete from audio_genres;
delete from album_art;
delete from video;
delete from videothumbnails;
delete from audio_genres_map;
delete from audio_playlists_map;
alter sequence files_id_seq restart with 1;
alter sequence artist_id_seq restart with 1;
alter sequence albums_id_seq restart with 1;
alter sequence audio_genres_id_seq restart with 1;
alter sequence audio_genres_map_id_seq restart with 1;
alter sequence audio_playlists_map_id_seq restart with 1;

leave;
enter 'media_external_2' using 'nopass';
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 100 from files);
delete from files where "_id" > (select max("_id") - 200 from files);
delete from files where "_id" > (select max("_id") - 200 from files);
delete from files where "_id" > (select max("_id") - 200 from files);
delete from files where "_id" > (select max("_id") - 200 from files);
delete from files where "_id" > (select max("_id") - 200 from files);
delete from files;
delete from thumbnails;
delete from artists;
delete from albums;
delete from audio_genres;
delete from album_art;
delete from video;
delete from videothumbnails;
delete from audio_genres_map;
delete from audio_playlists_map;
alter sequence files_id_seq restart with 1;
alter sequence artist_id_seq restart with 1;
alter sequence albums_id_seq restart with 1;
alter sequence audio_genres_id_seq restart with 1;
alter sequence audio_genres_map_id_seq restart with 1;
alter sequence audio_playlists_map_id_seq restart with 1;

leave;
--enter 'media_external_3' using 'nopass';
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 100 from files);
--delete from files where "_id" > (select max("_id") - 200 from files);
--delete from files where "_id" > (select max("_id") - 200 from files);
--delete from files where "_id" > (select max("_id") - 200 from files);
--delete from files where "_id" > (select max("_id") - 200 from files);
--delete from files where "_id" > (select max("_id") - 200 from files);
--delete from files;
--delete from thumbnails;
--delete from artists;
--delete from albums;
--delete from audio_genres;
--delete from album_art;
--delete from video;
--delete from videothumbnails;
--delete from audio_genres_map;
--delete from audio_playlists_map;
--alter sequence files_id_seq restart with 1;
--alter sequence artist_id_seq restart with 1;
--alter sequence albums_id_seq restart with 1;
--alter sequence audio_genres_id_seq restart with 1;
--alter sequence audio_genres_map_id_seq restart with 1;
--alter sequence audio_playlists_map_id_seq restart with 1;
--
--leave;
