LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_SHARED_LIBRARIES := librpc
LOCAL_SHARED_LIBRARIES += libutils
LOCAL_SHARED_LIBRARIES += libcutils

LOCAL_PREBUILT_LIBS:= libgps.so
LOCAL_MODULE_TAGS := optional

include $(BUILD_MULTI_PREBUILT)
