#! /bin/sh
#
#Copyright (c) 2013 Qualcomm Technologies, Inc.  All Rights Reserved.
#Qualcomm Technologies Proprietary and Confidential.

# qmi_ip   init.d script to start the Data Software's qmi_ip daemon

set -e

case "$1" in
  start)
        echo -n "Starting qmi_ip: "
        start-stop-daemon -S -b --exec /usr/bin/qmi_ip --pidfile /var/run/qmi_ip.pid
        echo "done"
        ;;
  stop)
        echo -n "Stopping qmi_ip: "
        start-stop-daemon -K -n qmi_ip
        echo "done"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage qmi_ip { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0