# BoardConfigVendor.mk
# Qualcomm Technologies proprietary product specific compile-time definitions.

BOARD_USES_GENERIC_AUDIO := false
USE_CAMERA_STUB := false

BOARD_USES_QCOM_HARDWARE := true
DYNAMIC_SHARED_LIBV8SO := true
DISABLE_CRANKSHAFT_SHARING := true
BOARD_USES_ADRENO := true
HAVE_ADRENO_SOURCE := true
HAVE_ADRENO_SC_SOURCE := true
HAVE_ADRENO_FIRMWARE := true
BOARD_USES_QCNE := true
USE_OPENGL_RENDERER := true
TARGET_USES_MDP3 := true
BOARD_USE_QCOM_LLVM_CLANG_RS := true
TARGET_USES_QCOM_MM_AUDIO := true
MM_AUDIO_OMX_ADEC_EVRC_DISABLED := false
MM_AUDIO_OMX_ADEC_QCELP13_DISABLED := false
MM_AUDIO_FTM_DISABLED := false
MM_AUDIO_MEASUREMENT_DISABLED := false
MM_AUDIO_VOEM_DISABLED := false
TARGET_NO_RPC := false
TARGET_USES_ION := true
TARGET_USES_ASHMEM := true
TARGET_HAVE_TSLIB := true

ifneq ($(BUILD_TINY_ANDROID), true)
  BOARD_VENDOR_QCOM_GPS_LOC_API_AMSS_VERSION := 50001
  BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := default
  BOARD_HAVE_BLUETOOTH := true
  BOARD_HAVE_QCOM_FM := true
  PROTEUS_DEVICE_API := false
  #HACK use Camera Stub
  BOARD_CAMERA_LIBRARIES := libcamera
  # Define respective statement to true to enable the ATH or WCN WLAN.
  BOARD_HAS_QCOM_WLAN := true
  CONFIG_EAP_PROXY := qmi
  BOARD_HAS_ATH_WLAN := true

  ifeq ($(findstring true,$(BOARD_HAS_ATH_WLAN) $(BOARD_HAS_QCOM_WLAN)),true)
    BOARD_WPA_SUPPLICANT_DRIVER := NL80211
    BOARD_HOSTAPD_DRIVER := NL80211
    WPA_SUPPLICANT_VERSION := VER_0_8_X
    HOSTAPD_VERSION := VER_0_8_X
    WIFI_CFG80211_DRIVER_MODULE_PATH := "/system/lib/modules/cfg80211.ko"
    WIFI_CFG80211_DRIVER_MODULE_NAME := "cfg80211"
    WIFI_CFG80211_DRIVER_MODULE_ARG  := ""
    WIFI_DRIVER_MODULE_PATH := "/system/lib/modules/wlan.ko"
    WIFI_DRIVER_MODULE_NAME := "wlan"
    WIFI_DRIVER_MODULE_ARG := ""

    WIFI_TEST_INTERFACE     := "sta"
    WIFI_DRIVER_FW_PATH_STA := "sta"
    WIFI_DRIVER_FW_PATH_AP  := "ap"
    WIFI_DRIVER_FW_PATH_P2P := "p2p"
  endif

  ifeq ($(BOARD_HAS_QCOM_WLAN), true)
    WIFI_SDIO_IF_DRIVER_MODULE_PATH := "/system/lib/modules/librasdioif.ko"
    WIFI_SDIO_IF_DRIVER_MODULE_NAME := "librasdioif"
    WIFI_SDIO_IF_DRIVER_MODULE_ARG  := ""
    BOARD_WLAN_DEVICE := qcwcn
  endif

  BOARD_USES_SRS_TRUEMEDIA := true
endif   # !BUILD_TINY_ANDROID
