#! /bin/sh
#
#Copyright (c) 2014 Qualcomm Technologies, Inc.  All Rights Reserved.
#Qualcomm Technologies Proprietary and Confidential.

# qti_ppp   init.d script to start the Data Software's qti_ppp daemon

set -e

case "$1" in
  start)
        echo -n "Starting qti_ppp: "
        echo "QTI_PPP:start" > /dev/kmsg
        start-stop-daemon -S -b --exec /usr/bin/qti_ppp
        echo "done"
        ;;
  stop)
        echo -n "Stopping qti_ppp: "
        start-stop-daemon -K -n qti_ppp
        echo "done"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage qti_ppp { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
