#!/bin/sh
################################################################################
# @file  /opt/qcom/bin/test/bt_test
# @brief Qualcomm BTS402x family Bluetooth SoC test script
# ------------------------------------------------------------------------------
# Copyright (C) 2008 Qualcomm Technologies, Inc.
# All Rights Reserved. Qualcomm Technologies Proprietary and Confidential.
# ------------------------------------------------------------------------------
################################################################################

## set -o errexit # quit at the first sign of trouble
## set -o xtrace # debug output

HCI=hci0
BTSTARTSTOP=/etc/init.d/bt

fail ()
{
	echo "Bluetooth: $*"
	exit 1
}

[ -x $BTSTARTSTOP ] || fail "startup script $BTSTARTSTOP not installed"
case $- in *x*)
	/bin/sh -x $BTSTARTSTOP start || fail "startup script $BTSTARTSTOP failed
	;;
    *)
	$BTSTARTSTOP start || fail "startup script $BTSTARTSTOP failed
	;;
esac

hciconfig -a | grep -q $HCI || fail "HCI interface 0 not attached"
hciconfig $HCI noscan || fail "hciconfig $HCI noscan failed"
sleep 4 # let BTSoC go to low power mode
hcitool -i $HCI inq >/dev/null || fail "hcitool cannot inquire"
if [ "$(cat /proc/bluetooth/sleep/proto)" != "1" ]
then
        echo msm_bt_sleep proto not enabled
else
        awk '/bluetooth/ {exit !$2}' /proc/interrupts || fail "no sleep interrupts"
fi
# don't test stop script this time around
# $BTSTARTSTOP stop || fail "shutdown script $BTSTARTSTOP failed"
echo "bt_test: Qualcomm Bluetooth System-on-Chip working" && exit 0
