
MODULE_NAME        := QMISVC
MODULE_ROOT        := ../../data-noship
MODULE_CFLAGS      := -DFEATURE_WAIT_FOR_MODEM_HACK
MODULE_C_SOURCES   := $(wildcard *.c)
MODULE_CPP_SOURCES := $(wildcard *.cpp)
MODULE_HEADERS     := $(wildcard *.h)
MODULE_LIB_LOC     := ../lib
MODULE_LIB_TARGET  := libqmi_services.so
MODULE_BIN_LOC     :=
MODULE_BIN_TARGET  :=

include $(MODULE_ROOT)/test.mk


