/******************************************************************************
  @file	 SubSystemShutdown.h
  @brief   Qualcomm Shutdown specific code.

  ---------------------------------------------------------------------------
  Copyright (c) 2013 Qualcomm Technologies, Inc. All Rights Reserved.
  Qualcomm Technologies Proprietary and Confidential.
  ---------------------------------------------------------------------------
 ******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qti_server_power_SubSystemShutdown */

#ifndef _Included_com_qti_server_power_SubSystemShutdown
#define _Included_com_qti_server_power_SubSystemShutdown
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qti_server_power_SubSystemShutdown
 * Method:    shutdown
 * Signature: ()
 */
JNIEXPORT jint JNICALL Java_com_qti_server_power_SubSystemShutdown_shutdown
    (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
