
MODULE_NAME        := CONFIGDB
MODULE_CFLAGS      := -DFEATURE_XMLLIB -DFEATURE_DSUTILS_OFFTARGET
MODULE_ROOT        := ../../../data-noship
MODULE_C_SOURCES   := $(wildcard *.c)
MODULE_CPP_SOURCES := $(wildcard *.cpp)
MODULE_HEADERS     := $(wildcard *.h)
MODULE_INCS        := -I../../../xmllib/inc
MODULE_LIB_LOC     := ../lib
MODULE_LIB_TARGET  := libconfigdb.so
MODULE_BIN_LOC     :=
MODULE_BIN_TARGET  :=

include $(MODULE_ROOT)/test.mk


